/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectinterface;

/**
 *
 * @author COMPUTER-12
 */
public class frm_college extends javax.swing.JFrame {

    /**
     * Creates new form frm_college
     */
    public frm_college() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        c3combo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        n3txt = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        d3combo = new javax.swing.JComboBox<>();
        s3combo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        college = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c3combo1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        n3txt1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        d3combo1 = new javax.swing.JComboBox<>();
        s3combo1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jRadioButton23 = new javax.swing.JRadioButton();
        jRadioButton24 = new javax.swing.JRadioButton();
        jRadioButton25 = new javax.swing.JRadioButton();
        jRadioButton26 = new javax.swing.JRadioButton();
        sbtn = new javax.swing.JButton();
        ebtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cnbtn = new javax.swing.JButton();
        jRadioButton27 = new javax.swing.JRadioButton();
        jRadioButton28 = new javax.swing.JRadioButton();

        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 130, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Department");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(520, 120, 110, 40);

        c3combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3combo.setText("Course");
        jPanel2.add(c3combo);
        c3combo.setBounds(210, 180, 90, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Semester");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 180, 120, 40);

        n3txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel2.add(n3txt);
        n3txt.setBounds(290, 130, 170, 40);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(300, 180, 160, 40);

        d3combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));
        jPanel2.add(d3combo);
        d3combo.setBounds(630, 120, 150, 30);

        s3combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s3combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        jPanel2.add(s3combo);
        s3combo.setBounds(640, 190, 140, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Directions:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 280, 200, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 320, 632, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("A higher score indicates a stronger agreement with the statement");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(0, 360, 620, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("QUESTIONS:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(0, 410, 108, 22);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("1.The institution takes active interest in promoting iv,student exchanges,internships         :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(0, 450, 650, 22);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("2. Instituion provide multiple environment to learn and grow                                         :");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(0, 490, 642, 22);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("3.Safety in college premises                                                                                        :");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(0, 530, 644, 22);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("4.How likely you recommend this college to others                                                       :");
        jPanel2.add(jLabel21);
        jLabel21.setBounds(0, 580, 645, 22);

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("5.Do you feel job competent when you move from this college                                      :");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(0, 620, 646, 22);
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(660, 490, 25, 25);
        jPanel2.add(jRadioButton4);
        jRadioButton4.setBounds(660, 450, 30, 25);

        college.setBackground(new java.awt.Color(255, 255, 255));
        college.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        college.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Name:");
        college.add(jLabel15);
        jLabel15.setBounds(200, 130, 70, 40);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Department");
        college.add(jLabel16);
        jLabel16.setBounds(520, 120, 110, 40);

        c3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3combo1.setText("Course");
        college.add(c3combo1);
        c3combo1.setBounds(200, 180, 90, 40);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Semester");
        college.add(jLabel17);
        jLabel17.setBounds(510, 180, 120, 40);

        n3txt1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        college.add(n3txt1);
        n3txt1.setBounds(290, 130, 170, 40);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        college.add(jComboBox2);
        jComboBox2.setBounds(300, 180, 160, 40);

        d3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));
        college.add(d3combo1);
        d3combo1.setBounds(630, 130, 150, 30);

        s3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s3combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        college.add(s3combo1);
        s3combo1.setBounds(640, 190, 140, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Directions:");
        college.add(jLabel23);
        jLabel23.setBounds(0, 270, 170, 50);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");
        college.add(jLabel24);
        jLabel24.setBounds(0, 320, 632, 40);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("A higher score indicates a stronger agreement with the statement");
        college.add(jLabel25);
        jLabel25.setBounds(0, 370, 620, 40);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("QUESTIONS:");
        college.add(jLabel26);
        jLabel26.setBounds(0, 420, 108, 22);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("1.The institution takes active interest in promoting iv,student exchanges,internships         :");
        college.add(jLabel27);
        jLabel27.setBounds(0, 460, 650, 22);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("2. Instituion provide multiple environment to learn and grow                                         :");
        college.add(jLabel28);
        jLabel28.setBounds(0, 510, 642, 22);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("3.Safety in college premises                                                                                        :");
        college.add(jLabel29);
        jLabel29.setBounds(0, 560, 644, 22);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("4.How likely you recommend this college to others                                                       :");
        college.add(jLabel30);
        jLabel30.setBounds(0, 600, 645, 22);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("5.Do you feel job competent when you move from this college                                      :");
        college.add(jLabel31);
        jLabel31.setBounds(0, 650, 646, 22);

        jLabel32.setText("1");
        college.add(jLabel32);
        jLabel32.setBounds(660, 420, 20, 20);

        jLabel33.setText("5");
        college.add(jLabel33);
        jLabel33.setBounds(890, 420, 30, 20);
        college.add(jLabel36);
        jLabel36.setBounds(800, 410, 0, 0);
        college.add(jRadioButton5);
        jRadioButton5.setBounds(660, 650, 25, 25);
        college.add(jRadioButton6);
        jRadioButton6.setBounds(710, 510, 25, 25);
        college.add(jRadioButton7);
        jRadioButton7.setBounds(760, 460, 30, 25);
        college.add(jRadioButton8);
        jRadioButton8.setBounds(660, 510, 25, 25);
        college.add(jRadioButton9);
        jRadioButton9.setBounds(710, 600, 25, 25);
        college.add(jRadioButton1);
        jRadioButton1.setBounds(660, 600, 25, 25);

        jLabel7.setText("3");
        college.add(jLabel7);
        jLabel7.setBounds(770, 420, 20, 20);

        jLabel6.setText("2");
        college.add(jLabel6);
        jLabel6.setBounds(720, 420, 30, 20);

        jLabel8.setText("4");
        college.add(jLabel8);
        jLabel8.setBounds(830, 420, 30, 20);

        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });
        college.add(jRadioButton10);
        jRadioButton10.setBounds(710, 650, 25, 25);
        college.add(jRadioButton11);
        jRadioButton11.setBounds(710, 560, 25, 25);
        college.add(jRadioButton12);
        jRadioButton12.setBounds(760, 510, 30, 25);
        college.add(jRadioButton13);
        jRadioButton13.setBounds(760, 560, 30, 25);
        college.add(jRadioButton14);
        jRadioButton14.setBounds(760, 600, 30, 25);
        college.add(jRadioButton15);
        jRadioButton15.setBounds(820, 460, 30, 25);
        college.add(jRadioButton16);
        jRadioButton16.setBounds(710, 460, 30, 25);
        college.add(jRadioButton17);
        jRadioButton17.setBounds(820, 510, 30, 25);
        college.add(jRadioButton18);
        jRadioButton18.setBounds(820, 560, 30, 25);
        college.add(jRadioButton19);
        jRadioButton19.setBounds(820, 600, 30, 25);
        college.add(jRadioButton20);
        jRadioButton20.setBounds(880, 460, 30, 25);
        college.add(jRadioButton21);
        jRadioButton21.setBounds(760, 650, 30, 25);
        college.add(jRadioButton22);
        jRadioButton22.setBounds(880, 510, 30, 25);
        college.add(jRadioButton23);
        jRadioButton23.setBounds(880, 560, 30, 25);
        college.add(jRadioButton24);
        jRadioButton24.setBounds(880, 600, 30, 25);
        college.add(jRadioButton25);
        jRadioButton25.setBounds(880, 650, 30, 25);
        college.add(jRadioButton26);
        jRadioButton26.setBounds(820, 650, 30, 25);

        sbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sbtn.setText("SUBMIT");
        college.add(sbtn);
        sbtn.setBounds(390, 760, 103, 31);

        ebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ebtn.setText("EDIT");
        college.add(ebtn);
        ebtn.setBounds(600, 760, 120, 31);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" STUDENT'S FEEDBACK FORM");
        college.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 90);

        cnbtn.setBackground(new java.awt.Color(255, 255, 255));
        cnbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnbtn.setText("CANCEL");
        college.add(cnbtn);
        cnbtn.setBounds(810, 760, 107, 31);
        college.add(jRadioButton27);
        jRadioButton27.setBounds(660, 460, 25, 25);
        college.add(jRadioButton28);
        jRadioButton28.setBounds(660, 560, 25, 25);

        jPanel2.add(college);
        college.setBounds(0, 0, 1050, 890);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_college().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel c3combo;
    private javax.swing.JLabel c3combo1;
    private javax.swing.JButton cnbtn;
    private javax.swing.JPanel college;
    private javax.swing.JComboBox<String> d3combo;
    private javax.swing.JComboBox<String> d3combo1;
    private javax.swing.JButton ebtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton23;
    private javax.swing.JRadioButton jRadioButton24;
    private javax.swing.JRadioButton jRadioButton25;
    private javax.swing.JRadioButton jRadioButton26;
    private javax.swing.JRadioButton jRadioButton27;
    private javax.swing.JRadioButton jRadioButton28;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JLabel n3txt;
    private javax.swing.JLabel n3txt1;
    private javax.swing.JComboBox<String> s3combo;
    private javax.swing.JComboBox<String> s3combo1;
    private javax.swing.JButton sbtn;
    // End of variables declaration//GEN-END:variables
}
