/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Paul
 */
public class form_staff extends javax.swing.JFrame {

    /**
     * Creates new form form_staff
     */
    public form_staff() {
        initComponents();
    }
String up,ps;
    form_staff(String u, String p) {
        initComponents();
        this.up=u;
        this.ps=p;
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stnametxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        st2name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        st26 = new javax.swing.JRadioButton();
        st6btn = new javax.swing.JRadioButton();
        st7 = new javax.swing.JRadioButton();
        st8 = new javax.swing.JRadioButton();
        st9 = new javax.swing.JRadioButton();
        st10 = new javax.swing.JRadioButton();
        st11 = new javax.swing.JRadioButton();
        st16 = new javax.swing.JRadioButton();
        st21 = new javax.swing.JRadioButton();
        st31 = new javax.swing.JRadioButton();
        st36 = new javax.swing.JRadioButton();
        st41 = new javax.swing.JRadioButton();
        st46 = new javax.swing.JRadioButton();
        st51 = new javax.swing.JRadioButton();
        st12 = new javax.swing.JRadioButton();
        st17 = new javax.swing.JRadioButton();
        st22 = new javax.swing.JRadioButton();
        st27 = new javax.swing.JRadioButton();
        st32 = new javax.swing.JRadioButton();
        st37 = new javax.swing.JRadioButton();
        st42 = new javax.swing.JRadioButton();
        st47 = new javax.swing.JRadioButton();
        st52 = new javax.swing.JRadioButton();
        st13 = new javax.swing.JRadioButton();
        st18 = new javax.swing.JRadioButton();
        st23 = new javax.swing.JRadioButton();
        st28 = new javax.swing.JRadioButton();
        st33 = new javax.swing.JRadioButton();
        st38 = new javax.swing.JRadioButton();
        st43 = new javax.swing.JRadioButton();
        st48 = new javax.swing.JRadioButton();
        st53 = new javax.swing.JRadioButton();
        st14 = new javax.swing.JRadioButton();
        st19 = new javax.swing.JRadioButton();
        st24 = new javax.swing.JRadioButton();
        st29 = new javax.swing.JRadioButton();
        st34 = new javax.swing.JRadioButton();
        st39 = new javax.swing.JRadioButton();
        st44 = new javax.swing.JRadioButton();
        st49 = new javax.swing.JRadioButton();
        st54 = new javax.swing.JRadioButton();
        st15 = new javax.swing.JRadioButton();
        st20 = new javax.swing.JRadioButton();
        st25 = new javax.swing.JRadioButton();
        st30 = new javax.swing.JRadioButton();
        st35 = new javax.swing.JRadioButton();
        st40 = new javax.swing.JRadioButton();
        st45 = new javax.swing.JRadioButton();
        st50 = new javax.swing.JRadioButton();
        st55 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        st56btn = new javax.swing.JButton();
        st58btn = new javax.swing.JButton();
        fcombo1 = new javax.swing.JComboBox<>();
        fcombo2 = new javax.swing.JComboBox<>();
        fcombo3 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" STUDENT'S FEEDBACK FORM");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Teacher's name :");

        stnametxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Name :");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Department :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Course :");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Semester :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Directions:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("A higher score indicates a stronger agreement with the statement");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");

        jLabel13.setText("1");

        jLabel14.setText("2");

        jLabel15.setText("3");

        jLabel16.setText("4");

        jLabel17.setText("5");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel18.setText("1.The teacher covers the entire syllubus                                                                       :");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel19.setText("2.The tacher posses deep knowledge of the subject taught                                             :");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel20.setText("3.The teacher is puntual to the class                                                                             :");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel21.setText("4.The teacher encourages participation and disscussion in class                                       :");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel22.setText("5. The teacher pays attention to academically weaker students                                        :");
        jLabel22.setMaximumSize(new java.awt.Dimension(438, 45));
        jLabel22.setPreferredSize(new java.awt.Dimension(438, 45));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel23.setText("6. The teacher's attitude towards the student's is friendly and helpful                               :");
        jLabel23.setMaximumSize(new java.awt.Dimension(438, 45));
        jLabel23.setPreferredSize(new java.awt.Dimension(438, 45));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("7. Periodical assesments were conducted as per schedule                                               :");
        jLabel24.setPreferredSize(new java.awt.Dimension(438, 45));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("8.Question paper covers all the topics in the curriculum                                                  :");
        jLabel25.setPreferredSize(new java.awt.Dimension(438, 45));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel26.setText("9.Teacher is fair and unbiased in the evaluation process                                                  :");
        jLabel26.setPreferredSize(new java.awt.Dimension(438, 45));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("10.Teacher inspires me by his/her knowledge in the subject                                             :");
        jLabel27.setPreferredSize(new java.awt.Dimension(438, 45));

        buttonGroup5.add(st26);
        st26.setText("jRadioButton1");

        buttonGroup1.add(st6btn);
        st6btn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        st6btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st6btnActionPerformed(evt);
            }
        });

        buttonGroup1.add(st7);
        st7.setText("jRadioButton3");

        buttonGroup1.add(st8);
        st8.setText("jRadioButton4");

        buttonGroup1.add(st9);
        st9.setText("jRadioButton5");

        buttonGroup1.add(st10);
        st10.setText("jRadioButton6");

        buttonGroup2.add(st11);
        st11.setText("jRadioButton7");

        buttonGroup3.add(st16);
        st16.setText("jRadioButton8");
        st16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st16ActionPerformed(evt);
            }
        });

        buttonGroup4.add(st21);
        st21.setText("jRadioButton9");

        buttonGroup6.add(st31);
        st31.setText("jRadioButton10");

        buttonGroup7.add(st36);
        st36.setText("jRadioButton11");

        st41.setText("jRadioButton12");

        st46.setText("jRadioButton13");

        st51.setText("jRadioButton14");

        buttonGroup2.add(st12);
        st12.setText("jRadioButton15");

        buttonGroup3.add(st17);
        st17.setText("jRadioButton16");

        buttonGroup4.add(st22);
        st22.setText("jRadioButton17");

        buttonGroup5.add(st27);
        st27.setText("jRadioButton18");

        buttonGroup6.add(st32);
        st32.setText("jRadioButton19");

        buttonGroup7.add(st37);
        st37.setText("jRadioButton20");

        st42.setText("jRadioButton21");

        st47.setText("jRadioButton22");

        st52.setText("jRadioButton23");

        buttonGroup2.add(st13);
        st13.setText("jRadioButton24");

        buttonGroup3.add(st18);
        st18.setText("jRadioButton25");

        buttonGroup4.add(st23);
        st23.setText("jRadioButton26");

        buttonGroup5.add(st28);
        st28.setText("jRadioButton27");

        buttonGroup6.add(st33);
        st33.setText("jRadioButton28");

        buttonGroup7.add(st38);
        st38.setText("jRadioButton29");

        st43.setText("jRadioButton30");

        st48.setText("jRadioButton31");

        st53.setText("jRadioButton32");

        buttonGroup2.add(st14);
        st14.setText("jRadioButton33");

        buttonGroup3.add(st19);
        st19.setText("jRadioButton34");

        buttonGroup4.add(st24);
        st24.setText("jRadioButton35");

        buttonGroup5.add(st29);
        st29.setText("jRadioButton36");

        buttonGroup6.add(st34);
        st34.setText("jRadioButton37");

        buttonGroup7.add(st39);
        st39.setText("jRadioButton38");

        st44.setText("jRadioButton39");

        st49.setText("jRadioButton40");

        st54.setText("jRadioButton41");

        buttonGroup2.add(st15);
        st15.setText("jRadioButton42");

        buttonGroup3.add(st20);
        st20.setText("jRadioButton43");

        buttonGroup4.add(st25);
        st25.setText("jRadioButton44");

        buttonGroup5.add(st30);
        st30.setText("jRadioButton45");

        buttonGroup6.add(st35);
        st35.setText("jRadioButton47");

        buttonGroup7.add(st40);
        st40.setText("jRadioButton48");

        st45.setText("jRadioButton49");

        st50.setText("jRadioButton50");

        st55.setText("jRadioButton51");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("QUESTIONS:");

        st56btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        st56btn.setText("SUBMIT");
        st56btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st56btnActionPerformed(evt);
            }
        });

        st58btn.setBackground(new java.awt.Color(255, 255, 255));
        st58btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        st58btn.setText("BACK");
        st58btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                st58btnActionPerformed(evt);
            }
        });

        fcombo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fcombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));

        fcombo2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fcombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        fcombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fcombo2ActionPerformed(evt);
            }
        });

        fcombo3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fcombo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "1", "2", "3", "4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st6btn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(st26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(st21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(st31, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(st36, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(st41, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(st46, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(st51, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(st7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(st13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st28, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st33, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st38, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st43, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(st53, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(st52, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st47, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st42, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st37, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(st12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(st54, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st49, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st44, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(st9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(st10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(st55, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st45, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st40, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(st15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(st30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(74, 74, 74))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fcombo3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(st2name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(st56btn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(st58btn)
                .addGap(100, 100, 100))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st2name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(stnametxt)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fcombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(st7)
                                .addComponent(st8)
                                .addComponent(st9)
                                .addComponent(st10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(st6btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st11)
                    .addComponent(st12)
                    .addComponent(st13)
                    .addComponent(st14)
                    .addComponent(st15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st16)
                    .addComponent(st17)
                    .addComponent(st18)
                    .addComponent(st19)
                    .addComponent(st20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st21)
                    .addComponent(st22)
                    .addComponent(st23)
                    .addComponent(st24)
                    .addComponent(st25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st26)
                    .addComponent(st27)
                    .addComponent(st28)
                    .addComponent(st29)
                    .addComponent(st30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st31)
                    .addComponent(st32)
                    .addComponent(st33)
                    .addComponent(st34)
                    .addComponent(st35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st36)
                    .addComponent(st37)
                    .addComponent(st38)
                    .addComponent(st39)
                    .addComponent(st40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st41)
                    .addComponent(st42)
                    .addComponent(st43)
                    .addComponent(st44)
                    .addComponent(st45))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st46)
                    .addComponent(st47)
                    .addComponent(st48)
                    .addComponent(st49)
                    .addComponent(st50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st51)
                    .addComponent(st52)
                    .addComponent(st53)
                    .addComponent(st54)
                    .addComponent(st55))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(st56btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(st58btn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void st16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st16ActionPerformed

    private void st56btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st56btnActionPerformed
  try{
      String tname=stnametxt.getText();
      String sname=st2name.getText();
      String dep=fcombo1.getSelectedItem().toString();
      String cor=fcombo2.getSelectedItem().toString();
      String sem=fcombo3.getSelectedItem().toString();
      
      String Q1 = "";
            
            if(st6btn.isSelected()){
              Q1="1";
            }
            if(st7.isSelected()){
            Q1="2";
             }
            if(st8.isSelected()){
            Q1="3";
             }
            if(st9.isSelected()){
            Q1="4";
             }
            if(st10.isSelected()){
            Q1="5";
             }
        String Q2 = "";
            
            if(st11.isSelected()){
              Q2="1";
            }
            if(st12.isSelected()){
            Q2="2";
             }
            if(st13.isSelected()){
            Q2="3";
             }
            if(st14.isSelected()){
            Q2="4";
             }
            if(st15.isSelected()){
            Q2="5";
             }
            String Q3 = "";
            
            if(st16.isSelected()){
              Q3="1";
            }
            if(st17.isSelected()){
            Q3="2";
             }
            if(st18.isSelected()){
            Q3="3";
             }
            if(st19.isSelected()){
            Q3="4";
             }
            if(st20.isSelected()){
            Q3="5";
             }
            String Q4 = "";
            
            if(st21.isSelected()){
              Q4="1";
            }
            if(st22.isSelected()){
            Q4="2";
             }
            if(st23.isSelected()){
            Q4="3";
             }
            if(st24.isSelected()){
            Q4="4";
             }
            if(st25.isSelected()){
            Q4="5";
             }
            String Q5 = "";
            
            if(st26.isSelected()){
              Q5="1";
            }
            if(st27.isSelected()){
            Q5="2";
             }
            if(st28.isSelected()){
            Q5="3";
             }
            if(st29.isSelected()){
            Q5="4";
             }
            if(st30.isSelected()){
            Q5="5";
             }
            String Q6 = "";
            
            if(st31.isSelected()){
              Q6="1";
            }
            if(st32.isSelected()){
            Q6="2";
             }
            if(st33.isSelected()){
            Q6="3";
             }
            if(st34.isSelected()){
            Q6="4";
             }
            if(st35.isSelected()){
            Q6="5";
             }
            String Q7 = "";
            
            if(st36.isSelected()){
              Q7="1";
            }
            if(st37.isSelected()){
            Q7="2";
             }
            if(st38.isSelected()){
            Q7="3";
             }
            if(st39.isSelected()){
            Q7="4";
             }
            if(st40.isSelected()){
            Q7="5";
             }
            String Q8 = "";
            
            if(st41.isSelected()){
              Q8="1";
            }
            if(st42.isSelected()){
            Q8="2";
             }
            if(st43.isSelected()){
            Q8="3";
             }
            if(st44.isSelected()){
            Q8="4";
             }
            if(st45.isSelected()){
            Q8="5";
             }
            String Q9 = "";
            
            if(st46.isSelected()){
              Q9="1";
            }
            if(st47.isSelected()){
            Q9="2";
             }
            if(st48.isSelected()){
            Q9="3";
             }
            if(st49.isSelected()){
            Q9="4";
             }
            if(st50.isSelected()){
            Q9="5";
             }
            String Q10 = "";
            
            if(st51.isSelected()){
              Q10="1";
            }
            if(st52.isSelected()){
            Q10="2";
             }
            if(st53.isSelected()){
            Q10="3";
             }
            if(st54.isSelected()){
            Q10="4";
             }
            if(st55.isSelected()){
            Q10="5";
             }
           Connection con=dbconnection.getconnection();
            Statement st=con.createStatement();
            String query="insert into form_staff values('"+tname+"','"+sname+"','"+dep+"','"+cor+"','"+sem+"','"+Q1+"','"+Q2+"','"+Q3+"','"+Q4+"','"+Q5+"','"+Q6+"','"+Q7+"','"+Q8+"','"+Q9+"','"+Q10+"')";
           st.executeUpdate(query);
  }
  catch (SQLException ex) {
            Logger.getLogger(form_staff.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_st56btnActionPerformed

    private void st58btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st58btnActionPerformed
this.hide();
new std_page().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_st58btnActionPerformed

    private void st6btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_st6btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_st6btnActionPerformed

    private void fcombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fcombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fcombo2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JComboBox<String> fcombo1;
    private javax.swing.JComboBox<String> fcombo2;
    private javax.swing.JComboBox<String> fcombo3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton st10;
    private javax.swing.JRadioButton st11;
    private javax.swing.JRadioButton st12;
    private javax.swing.JRadioButton st13;
    private javax.swing.JRadioButton st14;
    private javax.swing.JRadioButton st15;
    private javax.swing.JRadioButton st16;
    private javax.swing.JRadioButton st17;
    private javax.swing.JRadioButton st18;
    private javax.swing.JRadioButton st19;
    private javax.swing.JRadioButton st20;
    private javax.swing.JRadioButton st21;
    private javax.swing.JRadioButton st22;
    private javax.swing.JRadioButton st23;
    private javax.swing.JRadioButton st24;
    private javax.swing.JRadioButton st25;
    private javax.swing.JRadioButton st26;
    private javax.swing.JRadioButton st27;
    private javax.swing.JRadioButton st28;
    private javax.swing.JRadioButton st29;
    private javax.swing.JTextField st2name;
    private javax.swing.JRadioButton st30;
    private javax.swing.JRadioButton st31;
    private javax.swing.JRadioButton st32;
    private javax.swing.JRadioButton st33;
    private javax.swing.JRadioButton st34;
    private javax.swing.JRadioButton st35;
    private javax.swing.JRadioButton st36;
    private javax.swing.JRadioButton st37;
    private javax.swing.JRadioButton st38;
    private javax.swing.JRadioButton st39;
    private javax.swing.JRadioButton st40;
    private javax.swing.JRadioButton st41;
    private javax.swing.JRadioButton st42;
    private javax.swing.JRadioButton st43;
    private javax.swing.JRadioButton st44;
    private javax.swing.JRadioButton st45;
    private javax.swing.JRadioButton st46;
    private javax.swing.JRadioButton st47;
    private javax.swing.JRadioButton st48;
    private javax.swing.JRadioButton st49;
    private javax.swing.JRadioButton st50;
    private javax.swing.JRadioButton st51;
    private javax.swing.JRadioButton st52;
    private javax.swing.JRadioButton st53;
    private javax.swing.JRadioButton st54;
    private javax.swing.JRadioButton st55;
    private javax.swing.JButton st56btn;
    private javax.swing.JButton st58btn;
    private javax.swing.JRadioButton st6btn;
    private javax.swing.JRadioButton st7;
    private javax.swing.JRadioButton st8;
    private javax.swing.JRadioButton st9;
    private javax.swing.JTextField stnametxt;
    // End of variables declaration//GEN-END:variables
}
