/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

import feedback.management.dbconnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER-12
 */
public class frm_college extends javax.swing.JFrame {

    /**
     * Creates new form frm_college
     */
    public frm_college() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ccombo = new javax.swing.JComboBox<>();
        s3combo = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        college = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        c3combo1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        d3combo1 = new javax.swing.JComboBox<>();
        s3combo1 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        c21 = new javax.swing.JRadioButton();
        c7 = new javax.swing.JRadioButton();
        c3 = new javax.swing.JRadioButton();
        c6 = new javax.swing.JRadioButton();
        c17 = new javax.swing.JRadioButton();
        c16 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        c22 = new javax.swing.JRadioButton();
        c12 = new javax.swing.JRadioButton();
        c8 = new javax.swing.JRadioButton();
        c13 = new javax.swing.JRadioButton();
        c18 = new javax.swing.JRadioButton();
        c4 = new javax.swing.JRadioButton();
        c2 = new javax.swing.JRadioButton();
        c9 = new javax.swing.JRadioButton();
        c14 = new javax.swing.JRadioButton();
        c19 = new javax.swing.JRadioButton();
        c5 = new javax.swing.JRadioButton();
        c23 = new javax.swing.JRadioButton();
        c10 = new javax.swing.JRadioButton();
        c15 = new javax.swing.JRadioButton();
        c20 = new javax.swing.JRadioButton();
        c25 = new javax.swing.JRadioButton();
        c24 = new javax.swing.JRadioButton();
        sbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cnbtn = new javax.swing.JButton();
        c = new javax.swing.JRadioButton();
        c11 = new javax.swing.JRadioButton();
        n3txt = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        jRadioButton3.setText("jRadioButton3");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Name:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(200, 130, 70, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Department");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(520, 120, 110, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Semester");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(510, 180, 120, 40);

        ccombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        ccombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        jPanel2.add(ccombo);
        ccombo.setBounds(290, 180, 170, 40);

        s3combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s3combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        jPanel2.add(s3combo);
        s3combo.setBounds(640, 190, 140, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(0, 320, 632, 40);

        college.setBackground(new java.awt.Color(255, 255, 255));
        college.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        college.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel15.setText("Name:");
        college.add(jLabel15);
        jLabel15.setBounds(200, 130, 70, 40);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("Department");
        college.add(jLabel16);
        jLabel16.setBounds(520, 120, 110, 40);

        c3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3combo1.setText("Course");
        college.add(c3combo1);
        c3combo1.setBounds(200, 180, 90, 40);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel17.setText("Semester");
        college.add(jLabel17);
        jLabel17.setBounds(510, 180, 120, 40);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        college.add(jComboBox2);
        jComboBox2.setBounds(300, 180, 160, 40);

        d3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        d3combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));
        college.add(d3combo1);
        d3combo1.setBounds(630, 130, 150, 30);

        s3combo1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        s3combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        college.add(s3combo1);
        s3combo1.setBounds(640, 190, 140, 30);

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setText("Directions:");
        college.add(jLabel23);
        jLabel23.setBounds(10, 270, 170, 50);

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel24.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");
        college.add(jLabel24);
        jLabel24.setBounds(0, 320, 632, 40);

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel25.setText("A higher score indicates a stronger agreement with the statement");
        college.add(jLabel25);
        jLabel25.setBounds(0, 370, 620, 40);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setText("QUESTIONS:");
        college.add(jLabel26);
        jLabel26.setBounds(0, 420, 108, 22);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel27.setText("1.The institution takes active interest in promoting iv,student exchanges,internships         :");
        college.add(jLabel27);
        jLabel27.setBounds(0, 460, 650, 22);

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel28.setText("2. Instituion provide multiple environment to learn and grow                                         :");
        college.add(jLabel28);
        jLabel28.setBounds(0, 510, 642, 22);

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel29.setText("3.Safety in college premises                                                                                        :");
        college.add(jLabel29);
        jLabel29.setBounds(0, 560, 644, 22);

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel30.setText("4.How likely you recommend this college to others                                                       :");
        college.add(jLabel30);
        jLabel30.setBounds(0, 600, 645, 22);

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel31.setText("5.Do you feel job competent when you move from this college                                      :");
        college.add(jLabel31);
        jLabel31.setBounds(0, 650, 646, 22);

        jLabel32.setText("1");
        college.add(jLabel32);
        jLabel32.setBounds(660, 420, 20, 20);

        jLabel33.setText("5");
        college.add(jLabel33);
        jLabel33.setBounds(890, 420, 30, 20);
        college.add(jLabel36);
        jLabel36.setBounds(800, 410, 0, 0);

        buttonGroup5.add(c21);
        college.add(c21);
        c21.setBounds(660, 650, 21, 21);

        buttonGroup2.add(c7);
        college.add(c7);
        c7.setBounds(710, 510, 21, 21);

        buttonGroup1.add(c3);
        college.add(c3);
        c3.setBounds(760, 460, 30, 21);

        buttonGroup2.add(c6);
        college.add(c6);
        c6.setBounds(660, 510, 21, 21);

        buttonGroup4.add(c17);
        college.add(c17);
        c17.setBounds(710, 600, 21, 21);

        buttonGroup4.add(c16);
        college.add(c16);
        c16.setBounds(660, 600, 21, 21);

        jLabel7.setText("3");
        college.add(jLabel7);
        jLabel7.setBounds(770, 420, 20, 20);

        jLabel6.setText("2");
        college.add(jLabel6);
        jLabel6.setBounds(720, 420, 30, 20);

        jLabel8.setText("4");
        college.add(jLabel8);
        jLabel8.setBounds(830, 420, 30, 20);

        buttonGroup5.add(c22);
        c22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c22ActionPerformed(evt);
            }
        });
        college.add(c22);
        c22.setBounds(710, 650, 21, 21);

        buttonGroup3.add(c12);
        college.add(c12);
        c12.setBounds(710, 560, 21, 21);

        buttonGroup2.add(c8);
        college.add(c8);
        c8.setBounds(760, 510, 30, 21);

        buttonGroup3.add(c13);
        college.add(c13);
        c13.setBounds(760, 560, 30, 21);

        buttonGroup4.add(c18);
        college.add(c18);
        c18.setBounds(760, 600, 30, 21);

        buttonGroup1.add(c4);
        college.add(c4);
        c4.setBounds(820, 460, 30, 21);

        buttonGroup1.add(c2);
        college.add(c2);
        c2.setBounds(710, 460, 30, 21);

        buttonGroup2.add(c9);
        college.add(c9);
        c9.setBounds(820, 510, 30, 21);

        buttonGroup3.add(c14);
        college.add(c14);
        c14.setBounds(820, 560, 30, 21);

        buttonGroup4.add(c19);
        college.add(c19);
        c19.setBounds(820, 600, 30, 21);

        buttonGroup1.add(c5);
        college.add(c5);
        c5.setBounds(880, 460, 30, 21);

        buttonGroup5.add(c23);
        college.add(c23);
        c23.setBounds(760, 650, 30, 21);

        buttonGroup2.add(c10);
        college.add(c10);
        c10.setBounds(880, 510, 30, 21);

        buttonGroup3.add(c15);
        college.add(c15);
        c15.setBounds(880, 560, 30, 21);

        buttonGroup4.add(c20);
        college.add(c20);
        c20.setBounds(880, 600, 30, 21);

        buttonGroup5.add(c25);
        c25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c25ActionPerformed(evt);
            }
        });
        college.add(c25);
        c25.setBounds(880, 650, 30, 21);

        buttonGroup5.add(c24);
        college.add(c24);
        c24.setBounds(820, 650, 30, 21);

        sbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sbtn.setText("SUBMIT");
        sbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbtnActionPerformed(evt);
            }
        });
        college.add(sbtn);
        sbtn.setBounds(390, 760, 103, 31);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" STUDENT'S FEEDBACK FORM");
        college.add(jLabel1);
        jLabel1.setBounds(0, 0, 1050, 90);

        cnbtn.setBackground(new java.awt.Color(255, 255, 255));
        cnbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cnbtn.setText("BACK");
        cnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnbtnActionPerformed(evt);
            }
        });
        college.add(cnbtn);
        cnbtn.setBounds(810, 760, 85, 31);

        buttonGroup1.add(c);
        college.add(c);
        c.setBounds(660, 460, 21, 21);

        buttonGroup3.add(c11);
        college.add(c11);
        c11.setBounds(660, 560, 21, 21);

        n3txt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        college.add(n3txt);
        n3txt.setBounds(290, 122, 170, 40);

        jPanel2.add(college);
        college.setBounds(0, 0, 1050, 890);

        jTextField1.setText("jTextField1");
        jPanel2.add(jTextField1);
        jTextField1.setBounds(290, 122, 180, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1050, 890);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void c22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c22ActionPerformed

    private void sbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbtnActionPerformed
        try {
            String cname=n3txt.getText();
            String cdep=d3combo1.getSelectedItem().toString();
            String ccor=ccombo.getSelectedItem().toString();
            String csem=s3combo.getSelectedItem().toString();
            String c1 = "";
            
            if(c.isSelected()){
              c1="1";
            }
            if(c2.isSelected()){
            c1="2";
             }
            if(c3.isSelected()){
            c1="3";
             }
            if(c4.isSelected()){
            c1="4";
             }
            if(c5.isSelected()){
            c1="5";
             }
            
            String c2 = "";
            
            if(c6.isSelected()){
              c2="1";
            }
            if(c7.isSelected()){
            c2="2";
             }
            if(c8.isSelected()){
            c2="3";
             }
            if(c9.isSelected()){
            c2="4";
             }
            if(c10.isSelected()){
           c2="5";
             }
            
            String c3 = "";
            
            if(c11.isSelected()){
              c3="1";
            }
            if(c12.isSelected()){
            c3="2";
             }
            if(c13.isSelected()){
           c3="3";
             }
            if(c14.isSelected()){
            c3="4";
             }
            if(c15.isSelected()){
            c3="5";
             }
            
            String c4 = "";
            
            if(c16.isSelected()){
              c4="1";
            }
            if(c17.isSelected()){
            c4="2";
             }
            if(c18.isSelected()){
            c4="3";
             }
            if(c19.isSelected()){
            c4="4";
             }
            if(c20.isSelected()){
            c4="5";
             }
            
            String c5 = "";
            
            if(c21.isSelected()){
              c5="1";
            }
            if(c22.isSelected()){
           c5="2";
             }
            if(c23.isSelected()){
            c5="3";
             }
            if(c24.isSelected()){
            c5="4";
             }
            if(c25.isSelected()){
            c5="5";
             }
            
             //Connection con=db.dbconnection.getConnection();
            Connection con=dbconnection.getconnection();
            Statement st=con.createStatement();
           
             String query="insert into form_col values('"+cname+"','"+cdep+"','"+ccor+"','"+csem+"','"+c1+"','"+c2+"','"+c3+"','"+c4+"','"+c5+"')";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane," successfull");

    
       
        } catch (SQLException ex) {
            Logger.getLogger(frm_college.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_sbtnActionPerformed

    private void cnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnbtnActionPerformed
this.hide();
new std_page().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_cnbtnActionPerformed

    private void c25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c25ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_college().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JRadioButton c;
    private javax.swing.JRadioButton c10;
    private javax.swing.JRadioButton c11;
    private javax.swing.JRadioButton c12;
    private javax.swing.JRadioButton c13;
    private javax.swing.JRadioButton c14;
    private javax.swing.JRadioButton c15;
    private javax.swing.JRadioButton c16;
    private javax.swing.JRadioButton c17;
    private javax.swing.JRadioButton c18;
    private javax.swing.JRadioButton c19;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c20;
    private javax.swing.JRadioButton c21;
    private javax.swing.JRadioButton c22;
    private javax.swing.JRadioButton c23;
    private javax.swing.JRadioButton c24;
    private javax.swing.JRadioButton c25;
    private javax.swing.JRadioButton c3;
    private javax.swing.JLabel c3combo1;
    private javax.swing.JRadioButton c4;
    private javax.swing.JRadioButton c5;
    private javax.swing.JRadioButton c6;
    private javax.swing.JRadioButton c7;
    private javax.swing.JRadioButton c8;
    private javax.swing.JRadioButton c9;
    private javax.swing.JComboBox<String> ccombo;
    private javax.swing.JButton cnbtn;
    private javax.swing.JPanel college;
    private javax.swing.JComboBox<String> d3combo1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField n3txt;
    private javax.swing.JComboBox<String> s3combo;
    private javax.swing.JComboBox<String> s3combo1;
    private javax.swing.JButton sbtn;
    // End of variables declaration//GEN-END:variables
}
