

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;
import feedback.management.dbconnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER-25
 */
public class frmpage extends javax.swing.JFrame {

    /**
     * Creates new form frmpage
     */
    public frmpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        c3combo3 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        lcombo = new javax.swing.JComboBox<>();
        lcour = new javax.swing.JComboBox<>();
        lsem = new javax.swing.JComboBox<>();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        l2 = new javax.swing.JRadioButton();
        l1 = new javax.swing.JRadioButton();
        l16 = new javax.swing.JRadioButton();
        l6 = new javax.swing.JRadioButton();
        l11 = new javax.swing.JRadioButton();
        l8 = new javax.swing.JRadioButton();
        l12 = new javax.swing.JRadioButton();
        l17 = new javax.swing.JRadioButton();
        l5 = new javax.swing.JRadioButton();
        l21 = new javax.swing.JRadioButton();
        l22 = new javax.swing.JRadioButton();
        l25 = new javax.swing.JRadioButton();
        l4 = new javax.swing.JRadioButton();
        l7 = new javax.swing.JRadioButton();
        l3 = new javax.swing.JRadioButton();
        l13 = new javax.swing.JRadioButton();
        l18 = new javax.swing.JRadioButton();
        l23 = new javax.swing.JRadioButton();
        l9 = new javax.swing.JRadioButton();
        l14 = new javax.swing.JRadioButton();
        l19 = new javax.swing.JRadioButton();
        l24 = new javax.swing.JRadioButton();
        l10 = new javax.swing.JRadioButton();
        l15 = new javax.swing.JRadioButton();
        l20 = new javax.swing.JRadioButton();
        lcan = new javax.swing.JButton();
        lsub = new javax.swing.JButton();
        lname = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel32.setText("1");
        jPanel2.add(jLabel32);
        jLabel32.setBounds(660, 410, 20, 20);

        jLabel6.setText("2");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(720, 410, 30, 20);

        jLabel7.setText("3");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(770, 410, 20, 20);

        jLabel8.setText("4");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(830, 410, 30, 20);

        jLabel33.setText("5");
        jPanel2.add(jLabel33);
        jLabel33.setBounds(890, 410, 30, 20);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel34.setText("1");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(660, 410, 20, 20);

        jLabel30.setText("2");
        jPanel3.add(jLabel30);
        jLabel30.setBounds(720, 410, 30, 20);

        jLabel31.setText("3");
        jPanel3.add(jLabel31);
        jLabel31.setBounds(770, 410, 20, 20);

        jLabel35.setText("4");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(830, 410, 30, 20);

        jLabel36.setText("5");
        jPanel3.add(jLabel36);
        jLabel36.setBounds(890, 410, 30, 20);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel43.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel43.setText("A higher score indicates a stronger agreement with the statement");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(0, 360, 620, 40);

        jLabel50.setText("1");
        jPanel4.add(jLabel50);
        jLabel50.setBounds(660, 410, 20, 20);

        jLabel51.setText("2");
        jPanel4.add(jLabel51);
        jLabel51.setBounds(720, 410, 30, 20);

        jLabel52.setText("3");
        jPanel4.add(jLabel52);
        jLabel52.setBounds(770, 410, 20, 20);

        jLabel53.setText("4");
        jPanel4.add(jLabel53);
        jLabel53.setBounds(830, 410, 30, 20);

        jLabel54.setText("5");
        jPanel4.add(jLabel54);
        jLabel54.setBounds(890, 410, 30, 20);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText(" STUDENT'S FEEDBACK FORM");
        jPanel5.add(jLabel55);
        jLabel55.setBounds(0, 0, 980, 90);

        jLabel56.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel56.setText("Name:");
        jPanel5.add(jLabel56);
        jLabel56.setBounds(200, 130, 70, 40);

        jLabel57.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel57.setText("Department");
        jPanel5.add(jLabel57);
        jLabel57.setBounds(520, 120, 110, 40);

        c3combo3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        c3combo3.setText("Course");
        jPanel5.add(c3combo3);
        c3combo3.setBounds(210, 180, 90, 40);

        jLabel58.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel58.setText("Semester");
        jPanel5.add(jLabel58);
        jLabel58.setBounds(510, 180, 120, 40);

        lcombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));
        jPanel5.add(lcombo);
        lcombo.setBounds(630, 120, 150, 30);

        lcour.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lcour.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        jPanel5.add(lcour);
        lcour.setBounds(300, 180, 160, 40);

        lsem.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        jPanel5.add(lsem);
        lsem.setBounds(640, 190, 140, 30);

        jLabel59.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel59.setText("Directions:");
        jPanel5.add(jLabel59);
        jLabel59.setBounds(10, 280, 200, 40);

        jLabel60.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel60.setText("For each question indicate your level of agreement by choosing a score between 1 to 5. ");
        jPanel5.add(jLabel60);
        jLabel60.setBounds(0, 320, 632, 40);

        jLabel61.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel61.setText("A higher score indicates a stronger agreement with the statement");
        jPanel5.add(jLabel61);
        jLabel61.setBounds(0, 360, 620, 40);

        jLabel62.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel62.setText("QUESTIONS:");
        jPanel5.add(jLabel62);
        jLabel62.setBounds(0, 410, 108, 22);

        jLabel63.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel63.setText("1.Are the required number of titles in your subject available in your library         :");
        jPanel5.add(jLabel63);
        jLabel63.setBounds(0, 460, 590, 22);

        jLabel64.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel64.setText("2. Are you satisfied with the cataloging and arrangment in your library               :");
        jPanel5.add(jLabel64);
        jLabel64.setBounds(0, 510, 590, 22);

        jLabel65.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel65.setText("3.Are thelibrary staff co-operative and helpful                                                 :");
        jPanel5.add(jLabel65);
        jLabel65.setBounds(0, 550, 590, 22);

        jLabel66.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel66.setText("4.ARe you able to access internet as and when you require                              :");
        jPanel5.add(jLabel66);
        jLabel66.setBounds(0, 600, 580, 22);

        jLabel67.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel67.setText("5.Are you making use of educational online resources                                      :");
        jPanel5.add(jLabel67);
        jLabel67.setBounds(0, 650, 590, 22);

        jLabel68.setText("1");
        jPanel5.add(jLabel68);
        jLabel68.setBounds(660, 410, 20, 20);

        jLabel69.setText("2");
        jPanel5.add(jLabel69);
        jLabel69.setBounds(720, 410, 30, 20);

        jLabel70.setText("3");
        jPanel5.add(jLabel70);
        jLabel70.setBounds(770, 410, 20, 20);

        jLabel71.setText("4");
        jPanel5.add(jLabel71);
        jLabel71.setBounds(830, 410, 30, 20);

        jLabel72.setText("5");
        jPanel5.add(jLabel72);
        jLabel72.setBounds(890, 410, 30, 20);

        buttonGroup1.add(l2);
        jPanel5.add(l2);
        l2.setBounds(710, 460, 21, 21);

        buttonGroup1.add(l1);
        jPanel5.add(l1);
        l1.setBounds(660, 460, 21, 21);

        buttonGroup4.add(l16);
        jPanel5.add(l16);
        l16.setBounds(660, 600, 21, 21);

        buttonGroup2.add(l6);
        jPanel5.add(l6);
        l6.setBounds(660, 510, 21, 21);

        buttonGroup3.add(l11);
        jPanel5.add(l11);
        l11.setBounds(660, 550, 21, 21);

        buttonGroup2.add(l8);
        jPanel5.add(l8);
        l8.setBounds(760, 510, 21, 21);

        buttonGroup3.add(l12);
        jPanel5.add(l12);
        l12.setBounds(710, 550, 21, 21);

        buttonGroup4.add(l17);
        jPanel5.add(l17);
        l17.setBounds(710, 600, 21, 21);

        buttonGroup1.add(l5);
        jPanel5.add(l5);
        l5.setBounds(880, 460, 21, 21);

        buttonGroup5.add(l21);
        jPanel5.add(l21);
        l21.setBounds(660, 650, 21, 21);

        buttonGroup5.add(l22);
        jPanel5.add(l22);
        l22.setBounds(710, 650, 21, 21);

        buttonGroup5.add(l25);
        jPanel5.add(l25);
        l25.setBounds(880, 650, 21, 21);

        buttonGroup1.add(l4);
        jPanel5.add(l4);
        l4.setBounds(820, 460, 21, 20);

        buttonGroup2.add(l7);
        jPanel5.add(l7);
        l7.setBounds(710, 510, 21, 21);

        buttonGroup1.add(l3);
        jPanel5.add(l3);
        l3.setBounds(760, 460, 21, 21);

        buttonGroup3.add(l13);
        jPanel5.add(l13);
        l13.setBounds(760, 550, 21, 21);

        buttonGroup4.add(l18);
        jPanel5.add(l18);
        l18.setBounds(760, 600, 21, 21);

        buttonGroup5.add(l23);
        jPanel5.add(l23);
        l23.setBounds(760, 650, 21, 21);

        buttonGroup2.add(l9);
        jPanel5.add(l9);
        l9.setBounds(820, 510, 21, 21);

        buttonGroup3.add(l14);
        jPanel5.add(l14);
        l14.setBounds(820, 550, 21, 21);

        buttonGroup4.add(l19);
        jPanel5.add(l19);
        l19.setBounds(820, 600, 21, 21);

        buttonGroup5.add(l24);
        jPanel5.add(l24);
        l24.setBounds(820, 650, 21, 21);

        buttonGroup2.add(l10);
        jPanel5.add(l10);
        l10.setBounds(880, 510, 21, 21);

        buttonGroup3.add(l15);
        jPanel5.add(l15);
        l15.setBounds(880, 550, 21, 21);

        buttonGroup4.add(l20);
        jPanel5.add(l20);
        l20.setBounds(880, 600, 21, 21);

        lcan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lcan.setText("BACK");
        lcan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcanActionPerformed(evt);
            }
        });
        jPanel5.add(lcan);
        lcan.setBounds(793, 780, 120, 31);

        lsub.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lsub.setText("SUBMIT");
        lsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsubActionPerformed(evt);
            }
        });
        jPanel5.add(lsub);
        lsub.setBounds(440, 780, 103, 31);

        lname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel5.add(lname);
        lname.setBounds(300, 132, 160, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 0, 980, 950);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 980, 950);

        jTextField1.setText("jTextField1");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(300, 122, 160, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 980, 950);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 980, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsubActionPerformed
       try {
            String sttname=lname.getText();
            String dept=lcombo.getSelectedItem().toString();
            String course=lcour.getSelectedItem().toString();
            String semester=lsem.getSelectedItem().toString();
            String fl1 = "";
            
            if(l1.isSelected()){
              fl1="1";
            }
            if(l2.isSelected()){
            fl1="2";
             }
            if(l3.isSelected()){
            fl1="3";
             }
            if(l4.isSelected()){
            fl1="4";
             }
            if(l5.isSelected()){
            fl1="5";
             }
            
            String fl2 = "";
            
            if(l6.isSelected()){
              fl2="1";
            }
            if(l7.isSelected()){
            fl2="2";
             }
            if(l8.isSelected()){
            fl2="3";
             }
            if(l9.isSelected()){
            fl2="4";
             }
            if(l10.isSelected()){
           fl2="5";
             }
            
            String fl3 = "";
            
            if(l11.isSelected()){
              fl3="1";
            }
            if(l12.isSelected()){
            fl3="2";
             }
            if(l13.isSelected()){
           fl3="3";
             }
            if(l14.isSelected()){
            fl3="4";
             }
            if(l15.isSelected()){
            fl3="5";
             }
            
            String fl4 = "";
            
            if(l16.isSelected()){
              fl4="1";
            }
            if(l17.isSelected()){
            fl4="2";
             }
            if(l18.isSelected()){
            fl4="3";
             }
            if(l19.isSelected()){
            fl4="4";
             }
            if(l20.isSelected()){
            fl4="5";
             }
            
            String fl5 = "";
            
            if(l21.isSelected()){
              fl5="1";
            }
            if(l22.isSelected()){
           fl5="2";
             }
            if(l23.isSelected()){
            fl5="3";
             }
            if(l24.isSelected()){
           fl5="4";
             }
            if(l25.isSelected()){
            fl5="5";
             }
            
             //Connection con=db.dbconnection.getConnection();
            Connection con=dbconnection.getconnection();
            Statement st=con.createStatement();
           
             String query="insert into for_lib values('"+sttname+"','"+dept+"','"+course+"','"+semester+"','"+fl1+"','"+fl2+"','"+fl3+"','"+fl4+"','"+fl5+"')";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(rootPane," successfull");

    
       
        } catch (SQLException ex) {
            Logger.getLogger(frmpage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lsubActionPerformed

    private void lcanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcanActionPerformed
this.hide();
new std_page().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lcanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel c3combo3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton l1;
    private javax.swing.JRadioButton l10;
    private javax.swing.JRadioButton l11;
    private javax.swing.JRadioButton l12;
    private javax.swing.JRadioButton l13;
    private javax.swing.JRadioButton l14;
    private javax.swing.JRadioButton l15;
    private javax.swing.JRadioButton l16;
    private javax.swing.JRadioButton l17;
    private javax.swing.JRadioButton l18;
    private javax.swing.JRadioButton l19;
    private javax.swing.JRadioButton l2;
    private javax.swing.JRadioButton l20;
    private javax.swing.JRadioButton l21;
    private javax.swing.JRadioButton l22;
    private javax.swing.JRadioButton l23;
    private javax.swing.JRadioButton l24;
    private javax.swing.JRadioButton l25;
    private javax.swing.JRadioButton l3;
    private javax.swing.JRadioButton l4;
    private javax.swing.JRadioButton l5;
    private javax.swing.JRadioButton l6;
    private javax.swing.JRadioButton l7;
    private javax.swing.JRadioButton l8;
    private javax.swing.JRadioButton l9;
    private javax.swing.JButton lcan;
    private javax.swing.JComboBox<String> lcombo;
    private javax.swing.JComboBox<String> lcour;
    private javax.swing.JTextField lname;
    private javax.swing.JComboBox<String> lsem;
    private javax.swing.JButton lsub;
    // End of variables declaration//GEN-END:variables
}
