/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

/**
 *
 * @author Paul
 */
public class report_admin extends javax.swing.JFrame {

       String course;

    /**
     * Creates new form report_admin
     */
    public report_admin() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        repbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comborep = new javax.swing.JComboBox<>();
        combodept = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        repbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        repbtn.setText("VIEW");
        repbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repbtnActionPerformed(evt);
            }
        });
        jPanel3.add(repbtn);
        repbtn.setBounds(550, 250, 114, 35);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("VIEW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(550, 429, 115, 40);

        comborep.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        comborep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administration", "Library", "College" }));
        comborep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comborepActionPerformed(evt);
            }
        });
        jPanel3.add(comborep);
        comborep.setBounds(280, 250, 247, 35);

        combodept.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        combodept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bvoc software development", "bvoc multimedia", "bvoc accounting&taxation", "bvoc banking&finance", "bvoc fashion technology", "bvoc Agriculture", "bsc maths", "bsc physics", "bsc chemistry", "bsc botany", "bsc zoology", "ba english", "ba sociology", "ba history", "ba political science", "bba", "bca", "bcom computer application", "bcom finance", " " }));
        combodept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combodeptActionPerformed(evt);
            }
        });
        jPanel3.add(combodept);
        combodept.setBounds(220, 429, 300, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTextField1.setText("To view department wise reports");
        jPanel3.add(jTextField1);
        jTextField1.setBounds(30, 360, 345, 45);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(10, 650, 94, 29);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("REPORT");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(0, 0, 810, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\anjana\\4thsem project\\pro pics\\f5.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 130, 810, 570);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 810, 700);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 890, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void repbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repbtnActionPerformed
        String rep = comborep.getSelectedItem().toString();
        if (rep.equals("Administration")) {
            new display_new().setVisible(true);
            this.dispose();

        } else if (rep.equals("Library")) {
            new display_library().setVisible(true);
            this.dispose();

        } else if (rep.equals("College")) {
            new displaycollege().setVisible(true);
            this.dispose();

        }

    }//GEN-LAST:event_repbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        course = combodept.getSelectedItem().toString();
        new display_courseby(course).setVisible(true);
        this.dispose();
        
//        if (course.equals("bvoc software development")) {
//           
//            new display_courseby(course).setVisible(true);
//            //string="bvoc";
//            //like this:
//        } else if (course.equals("bvoc multimedia")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bvoc accounting and taxation")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bvoc banking and finance")) {
//            new display_courseby(course).setVisible(true);
//
//           
//        } else if (course.equals("bvoc fashion technology")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bvoc agriculture")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bsc maths")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bsc physics")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bsc chemistry")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bsc botany")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bsc zoology")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("ba english")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("ba sociology")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("ba history")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("ba political science")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bba")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bca")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bcom computer application")) {
//            new display_courseby(course).setVisible(true);
//
//        } else if (course.equals("bcom finance")) {
//            new display_courseby(course).setVisible(true);
//
//        }
//TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new admin_page().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comborepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comborepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comborepActionPerformed

    private void combodeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combodeptActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_combodeptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(report_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(report_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(report_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(report_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new report_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combodept;
    private javax.swing.JComboBox<String> comborep;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton repbtn;
    // End of variables declaration//GEN-END:variables
}
