/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.management.Query;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Paul
 */
public class staff_reg extends javax.swing.JFrame {

    /**
     * Creates new form staff_reg
     */
    public staff_reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addtxt = new javax.swing.JTextArea();
        idtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        phtxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();
        qualtxt = new javax.swing.JTextField();
        dptcombo = new javax.swing.JComboBox<>();
        courcombo = new javax.swing.JComboBox<>();
        malebtn = new javax.swing.JRadioButton();
        femalebtn = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        pastxt = new javax.swing.JPasswordField();
        passtxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Staff ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 100, 247, 44);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 160, 247, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Address");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 220, 247, 76);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 420, 250, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Department");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(130, 310, 247, 50);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Course");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(130, 370, 247, 49);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Qualification");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 460, 250, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Phone NO");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(130, 510, 247, 50);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Email ID");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(130, 570, 247, 50);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(530, 790, 148, 47);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(120, 780, 148, 52);

        addtxt.setColumns(20);
        addtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addtxt.setRows(5);
        jScrollPane1.setViewportView(addtxt);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(400, 230, 260, 70);

        idtxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        jPanel1.add(idtxt);
        idtxt.setBounds(400, 110, 259, 50);

        nametxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(nametxt);
        nametxt.setBounds(400, 170, 260, 50);

        phtxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(phtxt);
        phtxt.setBounds(400, 520, 259, 40);

        emailtxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(emailtxt);
        emailtxt.setBounds(400, 570, 259, 40);

        qualtxt.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(qualtxt);
        qualtxt.setBounds(400, 460, 260, 50);

        dptcombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dptcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "Botany", "Buisness Administration", "Chemistry", "Commerce", "Computer Application", "English", "HIstory", "Maths", "Physics", "Political Science", "Sociology", "Vocational Studies", "Zoology", " " }));
        jPanel1.add(dptcombo);
        dptcombo.setBounds(400, 310, 260, 40);

        courcombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        courcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "BA.English", "BA.History", "BA.Sociology", "BA.Political Science", "BBA", "BCA", "BCOM.Finance", "BCOM.Computer Application", "BSc.Applied Physics", "BSc.Botany", "BSc.Chemistry", "BSc.Maths", "BSc.Zoology", "BVoc.Agriculture", "BVoc.Accounting and Taxation", "BVoc.Banking and Finance", "BVoc.Fashion Technology", "BVoc.Multimedia", "BVoc.Software Development", " ", " " }));
        jPanel1.add(courcombo);
        courcombo.setBounds(400, 359, 260, 40);

        malebtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        malebtn.setText("Male");
        malebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malebtnActionPerformed(evt);
            }
        });
        jPanel1.add(malebtn);
        malebtn.setBounds(400, 410, 65, 31);

        femalebtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        femalebtn.setText("Female");
        jPanel1.add(femalebtn);
        femalebtn.setBounds(540, 410, 81, 31);

        jPanel2.setLayout(null);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 893, 0);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("STAFF REGISTRATION");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(150, 16, 380, 60);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Username");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(130, 630, 200, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText("Password");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(130, 670, 250, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel14.setText("Confirm Password");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(130, 720, 240, 40);
        jPanel1.add(usertxt);
        usertxt.setBounds(400, 620, 260, 40);
        jPanel1.add(pastxt);
        pastxt.setBounds(400, 720, 260, 40);
        jPanel1.add(passtxt);
        passtxt.setBounds(400, 670, 260, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\anjana\\4thsem project\\pro pics\\regstaff.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, 6, 810, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            String staff_id=idtxt.getText();
            String name=nametxt.getText();
            String address=addtxt.getText();
            String dept=dptcombo.getSelectedItem().toString();
            String course=courcombo.getSelectedItem().toString();
            String gender = "";
            if(malebtn.isSelected()&& malebtn.isSelected()){
              gender="male";
            }
            if(femalebtn.isSelected()&& femalebtn.isSelected()){
             gender="female";
             }
            
          
            String qualification=qualtxt.getText();
            String phone_number=phtxt.getText();
            String email=emailtxt.getText();
            String username=usertxt.getText();
            String password=passtxt.getText();
            String confirmpassword=pastxt.getText();
            System.out.println("staff id is "+staff_id);
            System.out.println("Name of the staff is "+name);
            System.out.println("address of the staff "+address);
            System.out.println("Department is  "+dept);
            System.out.println("Course is "+course);
            System.out.println(gender);
            System.out.println("Qualification is "+qualification);
            System.out.println("phone number is "+phone_number);
            System.out.println("email id is "+email);
            System.out.println("Username "+username);
            System.out.println("Password "+password);
            System.out.println(" confirm Password "+confirmpassword);
            //Connection con=db.dbconnection.getConnection();
            Connection con=dbconnection.getconnection();
            Statement st=con.createStatement();
           
             String query="insert into staff_reg values('"+staff_id+"','"+name+"','"+address+"','"+dept+"','"+course+"','"+gender+"','"+qualification+"','"+phone_number+"','"+email+"','"+username+"','"+password+"')";
       st.executeUpdate(query);

    JOptionPane.showMessageDialog(rootPane," registration successfull");
       
        } 
catch (SQLException ex) {
            Logger.getLogger(staff_reg.class.getName()).log(Level.SEVERE, null, ex);
        }

      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.hide();
new admin_page().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void malebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malebtnActionPerformed
        ButtonGroup group= new ButtonGroup();
        group.add(malebtn);
        group.add(femalebtn);// TODO add your handling code here:
    }//GEN-LAST:event_malebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staff_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staff_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addtxt;
    private javax.swing.JComboBox<String> courcombo;
    private javax.swing.JComboBox<String> dptcombo;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JRadioButton femalebtn;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton malebtn;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JPasswordField pastxt;
    private javax.swing.JTextField phtxt;
    private javax.swing.JTextField qualtxt;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
