/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPUTER-12
 */
public class std_reg extends javax.swing.JFrame {

    /**
     * Creates new form std_reg
     */
    public std_reg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        usertxt = new javax.swing.JTextField();
        regbutton = new javax.swing.JButton();
        canbt = new javax.swing.JButton();
        passtxt = new javax.swing.JPasswordField();
        depcombo = new javax.swing.JComboBox<>();
        coucombo = new javax.swing.JComboBox<>();
        semcombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cpasstxt = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("NAME OF THE STUDENT:");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(30, 80, 294, 34);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("DEPARTMENT:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 160, 294, 34);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("COURSE:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 240, 294, 24);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("SEMESTER:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 300, 294, 25);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("USERNAME:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 360, 294, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("PASSWORD:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 430, 294, 30);
        jPanel3.add(nametxt);
        nametxt.setBounds(60, 120, 294, 28);
        jPanel3.add(usertxt);
        usertxt.setBounds(70, 390, 290, 35);

        regbutton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        regbutton.setText("REGISTER");
        regbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbuttonActionPerformed(evt);
            }
        });
        jPanel3.add(regbutton);
        regbutton.setBounds(40, 630, 101, 32);

        canbt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        canbt.setText("CANCEL");
        canbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canbtActionPerformed(evt);
            }
        });
        jPanel3.add(canbt);
        canbt.setBounds(240, 630, 92, 32);
        jPanel3.add(passtxt);
        passtxt.setBounds(70, 460, 290, 32);

        depcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "bvoc", "zoology", "botany", "maths", "english", "sociology", "history", "bca", "bba", "physics", "bcom", "chemistry", "political s ience", " " }));
        depcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depcomboActionPerformed(evt);
            }
        });
        jPanel3.add(depcombo);
        depcombo.setBounds(60, 197, 294, 30);

        coucombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Choose--", "bvoc software development", "bvoc multimedia", "bvoc accounting&taxation", "bvoc banking&finance", "bvoc fashion technology", "bvoc Agriculture", "bsc maths", "bsc physics", "bsc chemistry", "bsc botany", "bsc zoology", "ba english", "ba sociology", "ba history", "ba political science", "bba", "bca", "bcom computer application", "bcom finance", "mcom", "msc maths", "ma sociology", "ma history", "msc botany", "ma english" }));
        coucombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coucomboActionPerformed(evt);
            }
        });
        jPanel3.add(coucombo);
        coucombo.setBounds(60, 271, 300, 30);

        semcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", "4", "5", "6" }));
        jPanel3.add(semcombo);
        semcombo.setBounds(70, 325, 290, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("CONFIRM PASSWORD");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 500, 294, 29);
        jPanel3.add(cpasstxt);
        cpasstxt.setBounds(70, 540, 290, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel9.setText("Student's Registration");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 20, 419, 46);

        jLabel10.setIcon(new javax.swing.ImageIcon("E:\\anjana\\4thsem project\\pro pics\\stdreg.png")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(-2, -4, 1160, 710);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1145, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbuttonActionPerformed
        try {
            String name=nametxt.getText();
            String dep=depcombo.getSelectedItem().toString();
            String course=coucombo.getSelectedItem().toString();
            String sem=semcombo.getSelectedItem().toString();
            String user=usertxt.getText();
            String password=passtxt.getText();
            String confirmpassword=cpasstxt.getText();
            System.out.println("Name of the student is "+name);
            System.out.println("Department is  "+dep);
            System.out.println("Course is "+course);
            System.out.println("Semester is "+sem);
            System.out.println("Username "+user);
            System.out.println("Password "+password);
            System.out.println(" confirm Password "+confirmpassword);
            //Connection con=db.dbconnection.getConnection();
            Connection con=dbconnection.getconnection();
            Statement st=con.createStatement();
             String query="insert into std_reg values(null,'"+name+"','"+dep+"','"+course+"','"+sem+"','"+user+"','"+password+"')";
       st.executeUpdate(query);
       JOptionPane.showMessageDialog(rootPane," registration successfull");
       
        } catch (SQLException ex) {
            Logger.getLogger(std_reg.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_regbuttonActionPerformed

    private void canbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canbtActionPerformed
this.hide();
new staff_page().setVisible(true);
    }//GEN-LAST:event_canbtActionPerformed

    private void depcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depcomboActionPerformed

    private void coucomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coucomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_coucomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(std_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(std_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(std_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(std_reg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new std_reg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canbt;
    private javax.swing.JComboBox<String> coucombo;
    private javax.swing.JPasswordField cpasstxt;
    private javax.swing.JComboBox<String> depcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nametxt;
    private javax.swing.JPasswordField passtxt;
    private javax.swing.JButton regbutton;
    private javax.swing.JComboBox<String> semcombo;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
