/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feedback.management;

/**
 *
 * @author Paul
 */
public class std_page extends javax.swing.JFrame {

    /**
     * Creates new form std_page
     */
    String u,p;
    public std_page() {
        initComponents();
    }

    std_page(String user, String password) {
        initComponents();
        this.u=user;
        this.p=password;
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        formcombo = new javax.swing.JComboBox<>();
        lobtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 165, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1257, 100);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FORMS");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(280, 170, 90, 50);

        formcombo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        formcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FACULTY", "ADMINISTRATION", "LIBRARY", "COLLEGE", " " }));
        formcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formcomboActionPerformed(evt);
            }
        });
        jPanel2.add(formcombo);
        formcombo.setBounds(370, 180, 170, 40);

        lobtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lobtn.setText("LOGOUT");
        lobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lobtnActionPerformed(evt);
            }
        });
        jPanel2.add(lobtn);
        lobtn.setBounds(330, 280, 170, 60);

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\anjana\\4thsem project\\pro pics\\stdpage.jpg")); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 1090, 540);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 100, 1100, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formcomboActionPerformed
    try{
       String f=formcombo.getSelectedItem().toString();
       if (f=="FACULTY"){
           new form_staff().setVisible(true);
       }
       else if(f=="ADMINISTRATION"){
           new form_administration().setVisible(true);
       }
       else if(f=="LIBRARY"){
           new frmpage().setVisible(true);
       } 
       else if(f=="COLLEGE"){
           new frm_college().setVisible (true);
       } 
    }catch(Exception e){
        
    }
    }//GEN-LAST:event_formcomboActionPerformed

    private void lobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lobtnActionPerformed
this.hide();
new login().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_lobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(std_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(std_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(std_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(std_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new std_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> formcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lobtn;
    // End of variables declaration//GEN-END:variables
}
